### ISSUE TITLE
people cant join me

### ISSUE THREAD

**Issue by clothingandprefabsrr** [DXXNS/Content-Warning-Cheat#10]
when i click join public it doesnt connect me to a server with other ppl and nobody can join me

**Comment by Gamersxp6248** [comment]
This is because content warning is attempting to prevent modded clients from matching with non modded clients. he's possible working on a fix but at the moment you will just have to get a vanilla friend to host and invite you.

**Comment by AkiraRiver** [comment]
Problem solved
