### ISSUE TITLE
ShopLifter mechanic broken

### ISSUE THREAD

**Issue by OhMyEnglishTeaBags** [DXXNS/Content-Warning-Cheat#6]
It allows you to click many items on the shop whilst having 0$, but you cannot actually order the items.

**Comment by ToaruRailgun** [comment]
unrelated, but spawning monsters also doesnt work (spawning items works fine though)

i assume its something from the new 1.9a update

**Comment by OhMyEnglishTeaBags** [comment]
> unrelated, but spawning monsters also doesnt work (spawning items works fine though)
> 
> i assume its something from the new 1.9a update

Monsters works for me. Try a fresh uninstall and reinstall of the game and then mod.

**Comment by AkiraRiver** [comment]
Monster spawning is now in host only cause of the game update and yea i'll try to fix the Shoplifting
