### ISSUE TITLE
When will the new monsters be added?

### ISSUE THREAD

**Issue by Spinmasterthehacker** [DXXNS/Content-Warning-Cheat#9]
or are they already, because im pretty sure some unused ones arent

**Comment by sevag13** [comment]
they aren't the cheat is getting updated later

**Comment by Spinmasterthehacker** [comment]
> they aren't the cheat is getting updated later

hopefully soon. i want to troll my friend some more lol

**Comment by AkiraRiver** [comment]
We've added at least some of them tell me if there's some that you don't find.
